version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - php
      - pgsql

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  pgsql:
    image: postgres
    ports:
      - "3422:5432"
    env_file:
      - env/pgsql.env
  
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel/
    depends_on:
      git:
        condition: service_completed_successfully
    

  git:
    build:
      context: dockerfiles
      dockerfile: git.Dockerfile
    env_file: 
        - env/git.env
    volumes:
      - ./src:/var/www/laravel
    

  
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    
    entrypoint: ["php", "/var/www/laravel/artisan"]